// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmkahguevsrvrrlkjzax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRta2FoZ3VldnNydnJybGtqemF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTgyMjEsImV4cCI6MjA2NDQ3NDIyMX0.O0w70xRSftt_ogXXjsidsa6gJThlgux7dVAIVT7nrKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);